### ISSUE TITLE
Cannot read property 'pageX' of null

### ISSUE THREAD

**Issue by mathewdbutton** [jbaysolutions/vue-grid-layout#36]
Hi all,

I've just stumbled across this vue library and I think it's brilliant, it's exactly what I'm looking for. I've been playing around with it and I'm having some problems. I'm attempting to get this simple example working and while everything renders just fine, I'm unable to drag and drop, or resize.

If I try and drag and drop, I get this error whenever I move the mouse around the page
> Uncaught TypeError: Cannot read property 'pageX' of null
    at InteractEvent (eval at <anonymous> (eval at <anonymous> (app.js:761)), <anonymous>:3473:57)
    at Interaction.dragMove (eval at <anonymous> (eval at <anonymous> (app.js:761)), <anonymous>:1967:30)
    at Interaction.pointerMove (eval at <anonymous> (eval at <anonymous> (app.js:761)), <anonymous>:1927:75)
    at HTMLDocument.eval (eval at <anonymous> (eval at <anonymous> (app.js:761)), <anonymous>:3349:36)

and whenever I try to resize I get this error

> Uncaught TypeError: Cannot set property 'h' of undefined
    at VueComponent.resizeEvent (eval at <anonymous> (eval at <anonymous> (http://localhost:8080/app.js:761:1)), <anonymous>:250:17)
    at VueComponent.boundFn [as resizeEvent] (eval at <anonymous> (http://localhost:8080/app.js:723:1), <anonymous>:124:14)
    at Vue$3.self.resizeEventHandler (eval at <anonymous> (eval at <anonymous> (http://localhost:8080/app.js:761:1)), <anonymous>:105:18)
    at Vue$3.Vue.$emit (eval at <anonymous> (eval at <anonymous> (http://localhost:8080/app.js:761:1)), <anonymous>:2545:16)
    at Vue$3.e.(anonymous function) [as $emit] (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/backend.js:1:6123)
    at VueComponent.handleResize (eval at <anonymous> (eval at <anonymous> (http://localhost:8080/app.js:761:1)), <anonymous>:471:22)
    at VueComponent.boundFn [as handleResize] (eval at <anonymous> (http://localhost:8080/app.js:723:1), <anonymous>:125:14)
    at Array.eval (eval at <anonymous> (eval at <anonymous> (http://localhost:8080/app.js:761:1)), <anonymous>:313:30)
    at Interactable.fire (eval at <anonymous> (eval at <anonymous> (http://localhost:8080/app.js:761:1)), <anonymous>:5007:33)
    at Interaction.resizeStart (eval at <anonymous> (eval at <anonymous> (http://localhost:8080/app.js:761:1)), <anonymous>:2034:25)
resizeEvent @ GridLayout.vue?e8af:241
boundFn @ vue.esm.js?65d7:124
self.resizeEventHandler @ GridLayout.vue?e8af:96
Vue.$emit @ vue.common.js?e881:2545
e.(anonymous function) @ backend.js:1
handleResize @ GridItem.vue?a853:469
boundFn @ vue.esm.js?65d7:125
(anonymous) @ GridItem.vue?a853:311
fire @ interact.js?3c23:5007
resizeStart @ interact.js?3c23:2034
start @ interact.js?3c23:1764
pointerMove @ interact.js?3c23:1920
(anonymous) @ interact.js?3c23:3349

Here is the vue component I'm attempting to get working.

```
<template>
  <div>
    <div class="row">
      <grid-layout
        :layout="layout"
        :col-num="12"
        :row-height="30"
        :is-draggable="true"
        :is-resizable="true"
        :vertical-compact="true"
        :margin="[10, 10]"
        :use-css-transforms="true"
      >
        <grid-item :key='widget.widget_type' v-for="(widget,index) in widgets"
                   :x="widget.col_start"
                   :y="widget.row_start"
                   :w="widget.width"
                   :h="widget.height"
                   :i="index">
           <div> steve </div>
        </grid-item>
      </grid-layout>
    </div>
  </div>
</template>

<script>
import VueLayout from 'vue-grid-layout'
export default {
  name: 'dashboard',
  components: {
    'GridLayout': VueLayout.GridLayout,
    'GridItem': VueLayout.GridItem
  },
  data () {
    return {
      widgets: [{ col_start: 1,
        row_start: 1,
        width: 2,
        height: 2 },
      {col_start: 3,
        row_start: 3,
        width: 2,
        height: 2}],
      layout: [
        {'x': 1, 'y': 1, 'w': 5, 'h': 5, 'i': '0'},
        {'x': 2, 'y': 2, 'w': 5, 'h': 5, 'i': '1'},
        {'x': 3, 'y': 3, 'w': 5, 'h': 5, 'i': '2'},
        {'x': 4, 'y': 4, 'w': 5, 'h': 5, 'i': '3'}
      ]
    }
  }
}
</script>
```

I also get this extra grid item on the page, even when my array of widgets is empty, not sure if it's related to that.

![screen shot 2017-03-21 at 9 46 57 am](https://cloud.githubusercontent.com/assets/1100707/24125273/04abdd5a-0e1c-11e7-93c7-377778a01a75.png)

Any help would be greatly appreciated. I suspect I'm just doing something silly so fingers crossed.

**Comment by gmsa** [comment]
You're using two differente arrays to supply the layout. You need to use the same on as the grid-layout "layout" and on the grid-item v-for:

```
   <div class="row">
      <grid-layout
        :layout="layout"
        :col-num="12"
        :row-height="30"
        :is-draggable="true"
        :is-resizable="true"
        :vertical-compact="true"
        :margin="[10, 10]"
        :use-css-transforms="true"
      >
        <grid-item :key='widget.i' v-for="(widget,index) in layout"
                   :x="widget.x"
                   :y="widget.y"
                   :w="widget.w"
                   :h="widget.h"
                   :i="widget.i">
           <div> steve </div>
        </grid-item>
      </grid-layout>
    </div>
```
