### ISSUE TITLE
SyntaxError: Unexpected token in vue3.

### ISSUE THREAD

**Issue by ygj6** [jbaysolutions/vue-grid-layout#521]
**Software version (please complete the following information):**
 - Vue Version [e.g. 3.0.0]
 - vue-grid-layout Version: [vue3](https://github.com/jbaysolutions/vue-grid-layout/tree/vue3)

**Describe the bug**
An error is reported when the `npm run build` is executed:
```
src/components/index.js → dist/vue-grid-layout.common.js, dist/vue-grid-layout.umd.min.js...
[!] (plugin commonjs) SyntaxError: Unexpected token (2:4) in vue-grid-layout\src\components\GridLayout.vue?vue&type=template&id=afbc0f80&lang.js
src\components\GridLayout.vue?vue&type=template&id=afbc0f80&lang.js (2:4)
1:
2:     <div ref="item" class="vue-grid-layout" :style="mergedStyle">
       ^
3:         <slot></slot>
4:         <grid-item class="vue-grid-placeholder"
SyntaxError: Unexpected token (2:4) in vue-grid-layout\src\components\GridLayout.vue?vue&type=template&id=afbc0f80&lang.js    at Object.pp$4.raise (vue-grid-layout\node_modules\rollup\dist\shared\rollup.js:15573:13)
    at Object.pp.unexpected (vue-grid-layout\node_modules\rollup\dist\shared\rollup.js:13265:8)
    at Object.pp$3.parseExprAtom (vue-grid-layout\node_modules\rollup\dist\shared\rollup.js:14972:10)
    at Object.pp$3.parseExprSubscripts (vue-grid-layout\node_modules\rollup\dist\shared\rollup.js:14775:19)
    at Object.pp$3.parseMaybeUnary (vue-grid-layout\node_modules\rollup\dist\shared\rollup.js:14752:17)
    at Object.parseMaybeUnary (vue-grid-layout\node_modules\rollup\dist\shared\rollup.js:19167:29)
    at Object.pp$3.parseExprOps (vue-grid-layout\node_modules\rollup\dist\shared\rollup.js:14687:19)
    at Object.pp$3.parseMaybeConditional (vue-grid-layout\node_modules\rollup\dist\shared\rollup.js:14670:19)
    at Object.pp$3.parseMaybeAssign (vue-grid-layout\node_modules\rollup\dist\shared\rollup.js:14638:19)
    at Object.pp$3.parseExpression (vue-grid-layout\node_modules\rollup\dist\shared\rollup.js:14604:19)
```

**Comment by gmsa** [comment]
fix merged to vue3 branch
