### ISSUE TITLE
@interactjs/arrange 版本好像不对 1.10.5。

### ISSUE THREAD

**Issue by luchuanqi** [jbaysolutions/vue-grid-layout#570]
error Couldn't find any versions for "@interactjs/arrange" that matches "1.10.5"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find any versions for "@interactjs/clone" that matches "1.10.5"
    at MessageError.ExtendableBuiltin (/usr/share/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/share/yarn/lib/cli.js:750:123)
    at Function.<anonymous> (/usr/share/yarn/lib/cli.js:50546:13)
    at Generator.next (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:310:30)
    at /usr/share/yarn/lib/cli.js:321:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find any versions for "@interactjs/multi-target" that matches "1.10.5"
    at MessageError.ExtendableBuiltin (/usr/share/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/share/yarn/lib/cli.js:750:123)
    at Function.<anonymous> (/usr/share/yarn/lib/cli.js:50546:13)
    at Generator.next (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:310:30)
    at /usr/share/yarn/lib/cli.js:321:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find any versions for "@interactjs/feedback" that matches "1.10.5"
    at MessageError.ExtendableBuiltin (/usr/share/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/share/yarn/lib/cli.js:750:123)
    at Function.<anonymous> (/usr/share/yarn/lib/cli.js:50546:13)
    at Generator.next (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:310:30)
    at /usr/share/yarn/lib/cli.js:321:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find any versions for "@interactjs/vue" that matches "1.10.5"
    at MessageError.ExtendableBuiltin (/usr/share/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/share/yarn/lib/cli.js:750:123)
    at Function.<anonymous> (/usr/share/yarn/lib/cli.js:50546:13)
    at Generator.next (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:310:30)
    at /usr/share/yarn/lib/cli.js:321:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find any versions for "@interactjs/react" that matches "1.10.5"
    at MessageError.ExtendableBuiltin (/usr/share/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/share/yarn/lib/cli.js:750:123)
    at Function.<anonymous> (/usr/share/yarn/lib/cli.js:50546:13)
    at Generator.next (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:310:30)
    at /usr/share/yarn/lib/cli.js:321:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by jinweijie** [comment]
Same issue: No matching version found for @interactjs/arrange@1.10.5.

**Comment by lizhongyue248** [comment]
Same issue: 
```
Error: Couldn't find any versions for "@interactjs/clone" that matches "1.10.5"
```

**Comment by panshiyu** [comment]
you can add "@interactjs/interactjs": "1.10.2" into package.json

**Comment by Nomercy10** [comment]
Does this issue get resolved by adding `@interactjs/interactjs: 1.10.2` ?
The library is expecting 1.10.5 which doesn't exist.
what would be the solution for this?

**Comment by czj2017** [comment]
the same; can't run "npm i"

**Comment by xinnai** [comment]
Same issue: No matching version found for @interactjs/arrange@1.10.5.

**Comment by gmsa** [comment]
Please follow the issue template guidelines

**Comment by gmsa** [comment]
https://github.com/taye/interact.js/issues/889
