### ISSUE TITLE
vue3: SyntaxError: The requested module '/node_modules/element-resize-detector/src/element-resize-detector.js?v=820a0926' does not provide an export named 'default' (at GridLayout.vue:1:194)

### ISSUE THREAD

**Issue by fairySusan** [jbaysolutions/vue-grid-layout#796]
**Software version (please complete the following information):**
vue："3.2.37",  vite:"2.6.4"   "vue-grid-layout-v3": "^3.0.3",
**Describe the bug**
```
SyntaxError:The requested module '/node_modules/element-resize-detector/src/element-resize-detector.js?v=820a0926' does not provide an export named 'default' (at GridLayout.vue:1:194)
```

**Comment by upthen** [comment]
I have met this problem too!
Have you resolved that?

**Comment by madhatter5501** [comment]
I have this same issue, did anyone get it working?

**Comment by Iris-mile** [comment]
I have this same issue, did anyone get it working?

**Comment by Iris-mile** [comment]
> I have this same issue, did anyone get it working?

I have this same issue, did anyone get it working?

**Comment by FBIshouxi** [comment]
https://blog.csdn.net/zhoudingding/article/details/128183788
vite.config.ts添加配置
```
    optimizeDeps: {
      include: ['element-resize-detector']
    }
```
